dist: bionic
sudo: required

language: java
jdk:
  - openjdk11

notifications:
  email:
    - michael@rabbitmq.com
    - acogoluegnes@vmware.com
addons:
  apt:
    sources:
      - sourceline: deb https://packages.erlang-solutions.com/ubuntu bionic contrib
        key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    packages:
      - esl-erlang=1:22.3.3-1
branches:
  only:
    - master
env:
  - HOP_RABBITMQCTL=rabbitmq/sbin/rabbitmqctl HOP_RABBITMQ_PLUGINS=rabbitmq/sbin/rabbitmq-plugins
before_script:
  - ./bin/set_up_infra.sh
  - ./bin/before_build.sh

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
script: ./gradlew check -i -s
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install: true
